### ISSUE TITLE
ERROR: Failed to map seat 'seat0' keyboard: XKBNotFound

### ISSUE THREAD

**Issue by JoshuaFern** [ifreund/waylock#30]
Hi, I'm a long time slock user new to wayland and waylock. I compiled the application but when I launch it I'm receiving the following error:

```
 △ ~ waylock -v
[2021-12-08T17:35:10Z][waylock::lock::input] ERROR: Failed to map seat 'seat0' keyboard: XKBNotFound
thread 'main' panicked at '[calloop] Encountered an orphan event: wl_keyboard@15 : keymap', /build/waylock-0.3.3-vendor.tar.gz/smithay-client-toolkit/src/event_loop.rs:39:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 △ ~ RUST_BACKTRACE=full waylock -v
[2021-12-08T17:35:15Z][waylock::lock::input] ERROR: Failed to map seat 'seat0' keyboard: XKBNotFound
thread 'main' panicked at '[calloop] Encountered an orphan event: wl_keyboard@15 : keymap', /build/waylock-0.3.3-vendor.tar.gz/smithay-client-toolkit/src/event_loop.rs:39:17
stack backtrace:
   0:     0x55d9eb83a416 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1ef07120adb99796
   1:     0x55d9eb8506dc - core::fmt::write::h59cc4b3dea155cce
   2:     0x55d9eb825215 - std::io::Write::write_fmt::he7e4fb4b70c5207a
   3:     0x55d9eb830b80 - std::panicking::default_hook::{{closure}}::h67c88fba3a1757d9
   4:     0x55d9eb830721 - std::panicking::default_hook::had51536d17f32530
   5:     0x55d9eb831133 - std::panicking::rust_panic_with_hook::hcdfd560c4f6afa56
   6:     0x55d9eb83a900 - std::panicking::begin_panic_handler::{{closure}}::h5e7abb77afe4762c
   7:     0x55d9eb83a564 - std::sys_common::backtrace::__rust_end_short_backtrace::hb15a1d01c910931c
   8:     0x55d9eb830c72 - rust_begin_unwind
   9:     0x55d9eb733e6b - std::panicking::begin_panic_fmt::ha0cdca991725ff2b
  10:     0x55d9eb758fdd - wayland_client::imp::queues::EventQueueInner::dispatch_pending::h4522165d54ddbb8f
  11:     0x55d9eb74c4b5 - <smithay_client_toolkit::event_loop::WaylandSource as calloop::sources::EventSource>::process_events::h84af86c7b90b1d3a
  12:     0x55d9eb74e7a4 - <core::cell::RefCell<calloop::sources::Dispatcher<Data,S,F>> as calloop::sources::EventDispatcher<Data>>::process_events::he91755ed74a470ff
  13:     0x55d9eb772093 - calloop::loop_logic::EventLoop<Data>::dispatch::hcb4732ea1bbeccf3
  14:     0x55d9eb768135 - waylock::lock::lock_screen::h895022591992ed9d
  15:     0x55d9eb760c2a - waylock::main::h0d78411fa2ad04a0
  16:     0x55d9eb761a63 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8ce6bb501f5f9fdf
  17:     0x55d9eb749f49 - std::rt::lang_start::{{closure}}::hf441b9423f9c3448
  18:     0x55d9eb8335f1 - std::rt::lang_start_internal::hc2cb966a7a4d713d
  19:     0x55d9eb761072 - main
  20:     0x7f5e19d8e780 - __libc_start_main
  21:     0x55d9eb7350ca - _start
  22:                0x0 - <unknown>
 △ ~ waylock -V    
waylock 0.3.3
```

Any idea?

**Comment by ifreund** [comment]
What compositor are you using? Do you have `libxkbcommon` installed? If so what version?

**Comment by JoshuaFern** [comment]
Sway, yes, 1.3.1

**Comment by JoshuaFern** [comment]
I wrote a Nix derivation for this package as it wasn't packaged yet, let me know if anything looks off to you:
```
{ lib, rustPlatform, fetchFromGitHub, stdenv, linux-pam, libxkbcommon }:

rustPlatform.buildRustPackage rec {
  pname = "waylock";
  version = "0.3.3";

  src = fetchFromGitHub {
    owner = "ifreund";
    repo = pname;
    rev = "v${version}";
    sha256 = "sha256-hIu+yzbnmALorkJywqcPY4fiqetarYCX/OPXq3ZKKh4=";
  };
  cargoSha256 = "euEswMbmvjdb9VFpVlIL5unadW1RVIh1Q9r3Jqwixhk=";

  buildInputs = [ linux-pam libxkbcommon ];

  meta = with lib; { maintainers = with maintainers; [ joshuafern ]; };
}
```
